const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const mongoose = require('mongoose');
const keys = require('../config/key');

const User = mongoose.model('users');

//Let's determine which data of the user object should be stored in the session
//serialize the user for the session
passport.serializeUser((user, done) => {
  done(null, user.id);
  //this is the unique id generated by mongoDB when we save it
});

//deserialize the user for the session
passport.deserializeUser((id, done) => {
  User.findById(id).then(user => {
    done(null, user);
  });
});

//let's tell passport to use googleStrategy auth/google
passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: '/auth/google/callback',
      proxy: true
    },
    async (accessToken, refreshToken, profile, done) => {
      const existingUser = await User.findOne({ googleId: profile.id });

      if (existingUser) {
        //we already have a record with the given profile ID
        done(null, existingUser);
      } else {
        //we dont have a user record so make a new record
        const user = await new User({ googleId: profile.id }).save();
        done(null, user);
      }
    }
  )
);
